TravelAgency/Controllers/OfferBoardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration; 
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using TravelAgency.Models;
using TravelAgencyAPI.Models;
using System.Linq;
using System;


namespace TravelAgency.Controllers
{
    [Route("[controller]")]
    public class OfferBoardController : Controller
    {
        private readonly HttpClient client;
        private readonly string WebApiPath;
        private readonly string WebApiPathHotel;
        private readonly string WebApiPathCity;
        private readonly string WebApiPathCountry;
        private readonly string WebApiPathBooking;
        private readonly IConfiguration _configuration;

        public OfferBoardController(IConfiguration configuration)
        {
            _configuration = configuration;
            WebApiPath = _configuration["TravelAgencyConfig:Url"];
            WebApiPathHotel = _configuration["TravelAgencyConfig:UrlHotel"];
            WebApiPathCity = _configuration["TravelAgencyConfig:UrlCity"];
            WebApiPathCountry = _configuration["TravelAgencyConfig:UrlCountry"];
            WebApiPathBooking = _configuration["TravelAgencyConfig:UrlBooking"];
            client = new HttpClient();
            client.DefaultRequestHeaders.Add("ApiKey", _configuration["TravelAgencyConfig:ApiKey"]);
        }


        [HttpGet("{offerID ?}/{cityID ?}/{numberOfPeople ?}")]
        public async Task<ActionResult> Index(int? offerID, int? cityID, int? numberOfPeople)
        {
            List<Offer> offers = new List<Offer>();
            List<Hotel> hotels = new List<Hotel>();
            List<City> cities = new List<City>();
            List<Country> countries = new List<Country>();
            HttpResponseMessage response = await client.GetAsync(WebApiPath);

            if (response.IsSuccessStatusCode)
            {
                    if (offerID != null)
                    {
                        response = await client.GetAsync(WebApiPath + "?offerID=" + offerID.ToString());
                    }
                offers = await response.Content.ReadAsAsync<List<Offer>>();
            }
            response = await client.GetAsync(WebApiPathHotel);
            if (response.IsSuccessStatusCode)
            {
                hotels = await response.Content.ReadAsAsync<List<Hotel>>();
            }
            response = await client.GetAsync(WebApiPathCity);
            if (response.IsSuccessStatusCode)
            {
                if (cityID != null)
                {
                    response = await client.GetAsync(WebApiPathCity + "?cityID=" + cityID.ToString());
                }
                cities = await response.Content.ReadAsAsync<List<City>>();
            }
            response = await client.GetAsync(WebApiPathCountry);
            if (response.IsSuccessStatusCode)
            {
                countries = await response.Content.ReadAsAsync<List<Country>>();
            }

            var joinModel =           from h in hotels
                                      join o in offers on h.ID equals o.HotelID
                                      join c in cities on h.CityID equals c.ID 
                                      join cr in countries on c.CountryID equals cr.ID into o2
                                      orderby o.FromDate
                                      from cr in o2.DefaultIfEmpty()
                                      select new OfferViewModel { Offer = o, Hotel = h, City = c , Country = cr};

            return View(joinModel);
        }
        [HttpGet("/Details/{id}")]
        public async Task<ActionResult> Details(int id)
        {
            Offer offer = new Offer();
            Hotel hotel = new Hotel();
            City city = new City();
            Country country = new Country();
            HttpResponseMessage response = await client.GetAsync(WebApiPath + "/" + id);
            if (response.IsSuccessStatusCode)
            {
                offer = await response.Content.ReadAsAsync<Offer>();
            }
            response = await client.GetAsync(WebApiPathHotel + "/" + offer.HotelID);
            if (response.IsSuccessStatusCode)
            {
                hotel = await response.Content.ReadAsAsync<Hotel>();
            }
            response = await client.GetAsync(WebApiPathCity + "/" + hotel.CityID);
            if (response.IsSuccessStatusCode)
            {
                city = await response.Content.ReadAsAsync<City>();
            }
            response = await client.GetAsync(WebApiPathCountry + "/" + city.CountryID);
            if (response.IsSuccessStatusCode)
            {
                country = await response.Content.ReadAsAsync<Country>();
            }

            var joinModel = new OfferViewModel { Offer = offer, Hotel = hotel, City = city, Country = country };

            return View(joinModel);
        }

        [HttpPost("/Created/{id}")]
        public async Task<ActionResult> Created(int id)
        {
            Booking booking = new Booking();
            booking.CustomerID = 1;
            booking.BookingStatusID = 5;
            booking.OfferID = id;
            booking.Date = DateTime.Now;
            
            HttpResponseMessage response = await client.PostAsJsonAsync(WebApiPathBooking, booking);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(Index));
            }
            
            return View();
        }
    }
}

TravelAgency/Views/OfferBoard/Created.cshtml
@model OfferViewModel

@{
    ViewData["Title"] = "Booking - Not Created";
}

<h1>Offer Details</h1>

<div>
    <h4>Offer</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <span>Booking was not created, please contact support</span>
        </div>
    </div>
</div>
<div>
    <a asp-controller="OfferBoard" asp-action="Index">Back to Offer Board</a>
</div>

TravelAgency/Views/OfferBoard/Details.cshtml
@model OfferViewModel

@{
    ViewData["Title"] = "Offer Details";
}

<h2>Offer Details</h2>

<div>
    <h4>Holiday</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-controller="OfferBoard" asp-action="Created" asp-route-id="@Model.Offer.ID">
                <div class="form-group">
                    <label asp-for="Hotel.Name" class="control-label">Hotel Name</label>
                    <input asp-for="Hotel.Name" class="form-control" value=@Model.Hotel.Name disabled />
                </div>
                <div class="form-group">
                    <label asp-for="Hotel.Address" class="control-label">Hotel Address</label>
                    <input asp-for="Hotel.Address" class="form-control" value=@Model.Hotel.Address disabled />
                </div>
                <div class="form-group">
                    <label asp-for="Country.Name" class="control-label">Destination (Country) </label>
                    <input asp-for="Country.Name" class="form-control" value=@Model.Country.Name disabled />
                </div>
                <div class="form-group">
                    <label asp-for="City.Name" class="control-label">Destination (City)</label>
                    <input asp-for="City.Name" class="form-control" value=@Model.City.Name disabled />
                </div>
                <div class="form-group">
                    <label class="control-label">Start Date</label>
                    <input class="form-control" value=@Model.Offer.FromDate.ToShortDateString() disabled />
                </div>
                <div class="form-group">
                    <label class="control-label">End Date</label>
                    <input class="form-control" value=@Model.Offer.ToDate.ToShortDateString() disabled />
                </div>
                <div class="form-group">
                    <label asp-for="Offer.NumberOfPeople" class="control-label">Number Of People</label>
                    <input asp-for="Offer.NumberOfPeople" class="form-control" value=@Model.Offer.NumberOfPeople disabled />
                </div>
                <div class="form-group">
                    <label asp-for="Offer.Price" class="control-label">Price (PLN)</label>
                    <input asp-for="Offer.Price" class="form-control" value=@Model.Offer.Price disabled />
                </div>
                <div class="form-group">
                    <input type="submit" value="Book it now !" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>
<div>
    <a asp-controller="OfferBoard" asp-action="Index">Back to Offer Board</a>
</div>

TravelAgency/Views/OfferBoard/Index.cshtml
@model IEnumerable<OfferViewModel>

@{
    ViewData["Title"] = "Offer Board";
}

<link rel="stylesheet" href="~/css/offerBoard.css" />

<h1>Holidays</h1>

<div class="offer-column-main">

    <div class="offer-list">
        @foreach (var item in Model)
        {
            <div>
                <article data-index=@item.Offer.ID class="offer">
                    <div class="offer-column-first">
                        <div class="photo-wrapper">
                            <img src="/icons/holidayPicture.jpg" alt="Holiday Picture" />
                        </div>
                    </div>
                    <div class="offer-column-second">
                        <div class="offer-description">
                            <span class="offer-title">Holidays</span>
                            <header>
                                <div class="offer-destination">
                                    @item.Country.Name / @item.City.Name
                                </div>
                                <h3 class="header-title">
                                    @item.Hotel.Name
                                <span class="stars">
                                    @for (int i = 0; i < @item.Hotel.StarRating; i++)
                                    {
                                        <img class="star" src="/icons/starIcon.png" />
                                    }
                                </span>
                            </h3>
                        </header>
                    </div>
                    <div class="offer-inner-border"></div>
                    <div class="offer-description-details">
                        <div class="offer-info">
                            <div class="offer-date">
                                <span>@item.Offer.FromDate.Date.ToShortDateString() - @item.Offer.ToDate.Date.ToShortDateString() (@item.Offer.NumberOfDays days)</span>
                            </div>
                            <div class="offer-info-details">
                                <div class="offer-price">
                                    <span class="current-price">@item.Offer.Price PLN / pp</span>
                                </div>
                                <a asp-controller="OfferBoard" asp-action="Details" asp-route-id="@item.Offer.ID" class="offer-link">
                                    <span class="link-text">Check the offer</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    }
    </div>
</div>